// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQMoX1oLW1SObCbo0OiS5KcXkwOSRu2u0',
    appId: '1:835662168538:web:ee227e242b00af70cd00e3',
    messagingSenderId: '835662168538',
    projectId: 'hala-bakeries-sales',
    authDomain: 'hala-bakeries-sales.firebaseapp.com',
    storageBucket: 'hala-bakeries-sales.firebasestorage.app',
    measurementId: 'G-HD22JSDPQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn59RPCea2w4wFqJCEN03xRd1dPUnMOVE',
    appId: '1:835662168538:android:a8b2acb5180e9100cd00e3',
    messagingSenderId: '835662168538',
    projectId: 'hala-bakeries-sales',
    storageBucket: 'hala-bakeries-sales.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSeQExDfH1kEHTz3Y8Gt1eHCA45V0U5NA',
    appId: '1:835662168538:ios:03ddd16f82302b7dcd00e3',
    messagingSenderId: '835662168538',
    projectId: 'hala-bakeries-sales',
    storageBucket: 'hala-bakeries-sales.firebasestorage.app',
    iosBundleId: 'com.example.halaBakeriesSales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSeQExDfH1kEHTz3Y8Gt1eHCA45V0U5NA',
    appId: '1:835662168538:ios:03ddd16f82302b7dcd00e3',
    messagingSenderId: '835662168538',
    projectId: 'hala-bakeries-sales',
    storageBucket: 'hala-bakeries-sales.firebasestorage.app',
    iosBundleId: 'com.example.halaBakeriesSales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQMoX1oLW1SObCbo0OiS5KcXkwOSRu2u0',
    appId: '1:835662168538:web:f07ed038777cbee7cd00e3',
    messagingSenderId: '835662168538',
    projectId: 'hala-bakeries-sales',
    authDomain: 'hala-bakeries-sales.firebaseapp.com',
    storageBucket: 'hala-bakeries-sales.firebasestorage.app',
    measurementId: 'G-WC1302NMCY',
  );
}
