import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import 'package:hala_bakeries_sales/features/auth/data/repositories/auth_repository.dart';
import 'package:hala_bakeries_sales/features/admin/data/repositories/branch_repository.dart';
import 'package:hala_bakeries_sales/features/admin/data/repositories/product_repository.dart';
import 'package:hala_bakeries_sales/features/admin/data/repositories/employee_repository.dart';
import 'package:hala_bakeries_sales/features/shared/data/repositories/transaction_repository.dart';
import 'package:hala_bakeries_sales/core/theme/app_theme.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/cubit/branch_cubit.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/pages/add_branch_screen.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/pages/branch_list_screen.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/cubit/product_cubit.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/pages/add_product_screen.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/pages/product_list_screen.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/cubit/employee_cubit.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/pages/add_employee_screen.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/pages/employee_list_screen.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/pages/admin_dashboard.dart';
import 'package:hala_bakeries_sales/features/auth/presentation/pages/login_screen.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/cubit/report_cubit.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/pages/reports_screen.dart';
import 'package:hala_bakeries_sales/features/employee/presentation/cubit/stock_cubit.dart';
import 'package:hala_bakeries_sales/features/employee/presentation/pages/stock_screen.dart';
import 'package:hala_bakeries_sales/features/employee/presentation/cubit/damage_cubit.dart';
import 'package:hala_bakeries_sales/features/employee/presentation/pages/damage_screen.dart';
import 'package:hala_bakeries_sales/features/employee/presentation/cubit/receive_cubit.dart';
import 'package:hala_bakeries_sales/features/employee/presentation/pages/receive_goods_screen.dart';
import 'package:hala_bakeries_sales/features/employee/presentation/pages/employee_dashboard.dart';
import 'package:hala_bakeries_sales/features/auth/presentation/pages/splash_screen.dart';
import 'package:hala_bakeries_sales/firebase_options.dart'; // This will be generated by the user

void main() async {
  WidgetsFlutterBinding.ensureInitialized();


  // UNCOMMENT THESE LINES:
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  runApp(const MyApp());
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import 'package:hala_bakeries_sales/features/auth/data/repositories/auth_repository.dart';
import 'package:hala_bakeries_sales/features/admin/data/repositories/branch_repository.dart';
import 'package:hala_bakeries_sales/features/admin/data/repositories/product_repository.dart'; // Added import
import 'package:hala_bakeries_sales/core/theme/app_theme.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/cubit/branch_cubit.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/pages/add_branch_screen.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/pages/branch_list_screen.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/cubit/product_cubit.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/pages/add_product_screen.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/pages/product_list_screen.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/cubit/employee_cubit.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/pages/add_employee_screen.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/pages/employee_list_screen.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/pages/admin_dashboard.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import 'package:hala_bakeries_sales/features/auth/data/repositories/auth_repository.dart';
import 'package:hala_bakeries_sales/features/admin/data/repositories/branch_repository.dart';
import 'package:hala_bakeries_sales/features/admin/data/repositories/product_repository.dart';
import 'package:hala_bakeries_sales/features/admin/data/repositories/employee_repository.dart';
import 'package:hala_bakeries_sales/features/employee/data/repositories/transaction_repository.dart'; // Added import for TransactionRepository
import 'package:hala_bakeries_sales/core/theme/app_theme.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/cubit/branch_cubit.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/pages/add_branch_screen.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/pages/branch_list_screen.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/cubit/product_cubit.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/pages/add_product_screen.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/pages/product_list_screen.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/cubit/employee_cubit.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/pages/add_employee_screen.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/pages/employee_list_screen.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/pages/admin_dashboard.dart';
import 'package:hala_bakeries_sales/features/auth/presentation/pages/login_screen.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/cubit/report_cubit.dart';
import 'package:hala_bakeries_sales/features/admin/presentation/pages/reports_screen.dart';
import 'package:hala_bakeries_sales/features/employee/presentation/cubit/stock_cubit.dart';
import 'package:hala_bakeries_sales/features/employee/presentation/pages/stock_screen.dart';
import 'package:hala_bakeries_sales/features/employee/presentation/cubit/damage_cubit.dart';
import 'package:hala_bakeries_sales/features/employee/presentation/pages/damage_screen.dart';
import 'package:hala_bakeries_sales/features/employee/presentation/cubit/receive_cubit.dart';
import 'package:hala_bakeries_sales/features/employee/presentation/pages/receive_goods_screen.dart';
import 'package:hala_bakeries_sales/features/employee/presentation/pages/employee_dashboard.dart';
import 'package:hala_bakeries_sales/features/auth/presentation/pages/splash_screen.dart';
import 'package:internet_connection_checker_plus/internet_connection_checker_plus.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:hala_bakeries_sales/features/auth/presentation/cubit/splash_cubit.dart'; // Added import for SplashCubit
import 'package:hala_bakeries_sales/features/auth/presentation/cubit/login_cubit.dart'; // Added import for LoginCubit
import 'package:hala_bakeries_sales/firebase_options.dart'; // This will be generated by the user

void main() async {
  WidgetsFlutterBinding.ensureInitialized();


  // UNCOMMENT THESE LINES:
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    final authRepository = AuthRepository();
    final branchRepository = BranchRepository();
    final productRepository = ProductRepository();
    final employeeRepository = EmployeeRepository();
    final transactionRepository = TransactionRepository(); // Instantiated TransactionRepository

    final GoRouter _router = GoRouter(
      initialLocation: '/',
      routes: [
        GoRoute(
          path: '/',
          builder: (context, state) => BlocProvider(
            create: (context) => SplashCubit(authRepository)..checkAuthStatus(),
            child: const SplashScreen(),
          ),
        ),
        GoRoute(
          path: '/login',
          builder: (context, state) => BlocProvider(
            create: (context) => LoginCubit(authRepository),
            child: const LoginScreen(),
          ),
        ),
        GoRoute(
          path: '/admin-dashboard',
          builder: (context, state) => const AdminDashboard(),
        ),
        GoRoute(
          path: '/admin/branches',
          builder: (context, state) {
            return BlocProvider(
              create: (context) => BranchCubit(branchRepository)..loadBranches(),
              child: const BranchListScreen(),
            );
          },
          routes: [
            GoRoute(
              path: 'add',
              builder: (context, state) {
                return BlocProvider(
                  create: (context) => BranchCubit(branchRepository), 
                  child: const AddBranchScreen(),
                );
              },
            ),
          ],
        ),
        GoRoute(
          path: '/admin/products',
          builder: (context, state) {
            return BlocProvider(
              create: (context) => ProductCubit(productRepository)..loadProducts(),
              child: const ProductListScreen(),
            );
          },
          routes: [
            GoRoute(
              path: 'add',
              builder: (context, state) {
                return BlocProvider(
                  create: (context) => ProductCubit(productRepository),
                  child: const AddProductScreen(),
                );
              },
            ),
          ],
        ),
        GoRoute(
          path: '/admin/employees',
          builder: (context, state) {
            return BlocProvider(
              create: (context) => EmployeeCubit(employeeRepository)..loadEmployees(),
              child: const EmployeeListScreen(),
            );
          },
          routes: [
            GoRoute(
              path: 'add',
              builder: (context, state) {
                return BlocProvider(
                  create: (context) => EmployeeCubit(employeeRepository),
                  child: const AddEmployeeScreen(),
                );
              },
            ),
          ],
        ),
        GoRoute(
          path: '/employee-dashboard',
          builder: (context, state) => const EmployeeDashboard(),
        ),
        GoRoute(
          path: '/employee/receive',
          builder: (context, state) {
            return BlocProvider(
              create: (context) => ReceiveCubit(productRepository, transactionRepository)..loadProducts(),
              child: const ReceiveGoodsScreen(),
            );
          },
        ),
        GoRoute(
          path: '/employee/damage',
          builder: (context, state) {
            return BlocProvider(
              create: (context) => DamageCubit(productRepository, transactionRepository)..loadProducts(),
      builder: (context, child) {
        return Directionality(
          textDirection: TextDirection.rtl, // Force RTL for Arabic
          child: Stack(
            children: [
              child!,
              const ConnectivityBanner(),
            ],
          ),
        );
      },
    );
  }
}

class ConnectivityBanner extends StatelessWidget {
  const ConnectivityBanner({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<InternetStatus>(
      stream: InternetConnection().onStatusChange,
      builder: (context, snapshot) {
        if (snapshot.hasData && snapshot.data == InternetStatus.disconnected) {
          return Positioned(
            bottom: 0,
            left: 0,
            right: 0,
            child: Material(
              color: Colors.red,
              child: Padding(
                padding: const EdgeInsets.all(8.0),
                child: Text(
                  'لا يوجد اتصال بالإنترنت - وضع العمل دون اتصال',
                  textAlign: TextAlign.center,
                  style: GoogleFonts.cairo(color: Colors.white),
                ),
              ),
            ),
          );
        }
        return const SizedBox.shrink();
      },
    );
  }
}
